#!/bin/bash

TESTDIR=$(dirname "$(pwd)/$0")

if [ $# = 1 ]; then
  TEST="$1"
  if ! [ -e "$TEST" ]; then
    echo "Could not find test $TEST"
    exit 1
  fi
fi


MANAGEDIR="$TESTDIR"
while ! [ -e "$MANAGEDIR/manage.py" ] && [ "$MANAGEDIR" != "/" ]; do
  MANAGEDIR=$(dirname "$MANAGEDIR")
done
MANAGE="$MANAGEDIR/manage.py"
if ! [ -e "$MANAGE" ]; then
  echo "Could not find manage.py in parent dirs"
  exit 1
fi

TESTSERVER_PID=""

function run_testserver {
  python $MANAGE testserver --addrport 8123 "$MANAGEDIR/ideaList/fixtures/auth.json" &
  TESTSERVER_PID=$!
  sleep 5 # give the server some time to start
}

function kill_testserver {
  if [ -n $TESTSERVER_PID ]; then
    kill $TESTSERVER_PID
  fi
  TESTSERVER_PID=""
}




if [ -n "$TEST" ]; then
  run_testserver
  windmill shell firefox http://127.0.0.1:8123/ideaList/ test="$TEST"
  kill_testserver
else
  # TODO: recursively iterate through all subdirectories of $TESTDIR with __init__.py

  run_testserver
  windmill shell firefox http://127.0.0.1:8123/ideaList/ test="$TESTDIR"
  kill_testserver

  run_testserver
  windmill shell firefox http://127.0.0.1:8123/ideaList/ test="$TESTDIR/with_items"
  kill_testserver
fi
