from windmill.authoring import WindmillTestClient

def test_set_item_url():
    client = WindmillTestClient(__name__)

    # set item 1 url (press enter)
    client.asserts.assertJS(js=u"$('#link_button').is(':hidden')")
    client.check(xpath=u"//li[@id='item_1']/input[@type='checkbox']")
    client.asserts.assertChecked(xpath=u"//li[@id='item_1']/input[@type='checkbox']")
    client.asserts.assertJS(js=u"$('#link_button').is(':visible')")
    client.asserts.assertJS(js=u"$('#url_input_container').is(':hidden')")
    client.asserts.assertJS(js=u"$('#item_1_link').is(':hidden')")
    client.click(id=u'link_button')
    client.waits.sleep(milliseconds=u'100')
    client.asserts.assertJS(js=u"$('#url_input_container').is(':visible')")
    client.type(id=u'url_input', text=u'http://google.com/')
    client.keyDown(id=u'url_input', options=u'13,false,false,false,false,false')
    client.waits.sleep(milliseconds=u'500')
    client.asserts.assertJS(js=u"$('#item_1_link').is(':visible')")
    client.asserts.assertJS(js=u"$('#item_1_link').attr('href') == 'http://google.com/'")
    client.asserts.assertJS(js=u"$('#link_button').is(':hidden')")

    # unset item 1 url (click submit button)
    client.check(xpath=u"//li[@id='item_1']/input[@type='checkbox']")
    client.asserts.assertChecked(xpath=u"//li[@id='item_1']/input[@type='checkbox']")
    client.asserts.assertJS(js=u"$('#url_input_container').is(':hidden')")
    client.asserts.assertJS(js=u"$('#item_1_link').is(':visible')")
    client.click(id=u'link_button')
    client.waits.sleep(milliseconds=u'100')
    client.asserts.assertJS(js=u"$('#url_input_container').is(':visible')")
    client.asserts.assertJS(js=u"$('#url_input').val() == 'http://google.com/'")
    client.type(id=u'url_input', text=u'')
    client.click(id=u'url_submit')
    client.waits.sleep(milliseconds=u'500')
    client.asserts.assertJS(js=u"$('#url_input_container').is(':hidden')")
    client.asserts.assertJS(js=u"$('#item_1_link').is(':hidden')")
    client.asserts.assertJS(js=u"$('#item_1_link').attr('href') == ''")

    # test canceling by unchecking while editing
    client.check(xpath=u"//li[@id='item_1']/input[@type='checkbox']")
    client.asserts.assertChecked(xpath=u"//li[@id='item_1']/input[@type='checkbox']")
    client.asserts.assertJS(js=u"$('#url_input_container').is(':hidden')")
    client.click(id=u'link_button')
    client.waits.sleep(milliseconds=u'100')
    client.asserts.assertJS(js=u"$('#url_input_container').is(':visible')")
    client.check(xpath=u"//li[@id='item_1']/input[@type='checkbox']")
    client.asserts.assertNotChecked(xpath=u"//li[@id='item_1']/input[@type='checkbox']")
    client.asserts.assertJS(js=u"$('#url_input_container').is(':hidden')")
